# Generated by Django 3.0.2 on 2023-02-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождение')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Почта')),
                ('drivers_licence', models.CharField(max_length=255, verbose_name='Права')),
                ('drivers_licence_img', models.ImageField(default='default.png', upload_to='users/')),
                ('drivers_series', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия прав')),
                ('drivers_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер прав')),
                ('experience', models.CharField(max_length=255, verbose_name='Стаж')),
                ('passport_doled_out', models.DateField(blank=True, null=True, verbose_name='Паспорт выдан')),
                ('passport_series', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер паспорт')),
                ('passport_issued', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан')),
                ('passport_img', models.ImageField(default='default.png', upload_to='users/')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
        ),
    ]
