# Generated by Django 3.0.2 on 2023-02-03 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Сумма')),
                ('car_profit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car', verbose_name='ID Машины')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_reserve_id', models.IntegerField(blank=True, null=True)),
                ('outcome_remark', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome_amount', models.IntegerField(verbose_name='Сумма')),
                ('order_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
                ('car_outcome_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car', verbose_name='ID Машины')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_reserve_id', models.IntegerField()),
                ('income_amount', models.IntegerField(verbose_name='Сумма')),
                ('order_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
                ('car_income_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car', verbose_name='ID Машины')),
            ],
        ),
    ]
