# Generated by Django 4.1.7 on 2023-02-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='outcome_remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарии'),
        ),
    ]
