# Generated by Django 3.0.2 on 2023-02-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Service name')),
                ('name_rus', models.CharField(max_length=255, verbose_name='Наименование услуги')),
                ('description', models.CharField(max_length=255, verbose_name='Service description')),
                ('description_rus', models.CharField(max_length=255, verbose_name='Описание услуги')),
                ('price', models.IntegerField(verbose_name='Цена услуги')),
                ('image', models.ImageField(default='default.png', upload_to='service/', verbose_name='Картинка услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now=True)),
                ('total', models.IntegerField()),
                ('total_summ', models.IntegerField()),
                ('territory_of_use', models.CharField(blank=True, max_length=255, null=True, verbose_name='Территория использования ТС')),
                ('reserve_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.Reserve')),
            ],
        ),
    ]
