# Generated by Django 3.0.2 on 2023-02-03 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_car_js', models.CharField(max_length=255)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('registration_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('Бронь', 'Бронь'), ('Выдана', 'Выдана'), ('Подтвержденная бронь', 'Подтвержденная бронь'), ('Тех Работы', 'Тех Работы')], max_length=100)),
                ('outcome_res_amount', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_days', models.IntegerField(blank=True, default=0, null=True)),
                ('total_summ', models.IntegerField(blank=True, default=0, null=True)),
                ('change_summ', models.IntegerField(blank=True, default=0, null=True)),
                ('reserve_car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Car')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Users')),
            ],
        ),
    ]
