# Generated by Django 3.0.2 on 2023-02-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Function Name')),
                ('title_rus', models.CharField(max_length=255, verbose_name='Функции машины')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_owner', models.CharField(max_length=255, verbose_name='Собственник ТС')),
                ('car_number', models.CharField(max_length=255, verbose_name='Номер машины')),
                ('title', models.CharField(max_length=255, verbose_name='Название машины')),
                ('description', models.TextField(verbose_name='Car description')),
                ('car_price', models.IntegerField(verbose_name='Цена машины')),
                ('description_rus', models.TextField(verbose_name='Описание машины')),
                ('car_color', models.CharField(max_length=255, verbose_name='Car Color')),
                ('car_color_rus', models.CharField(max_length=255, verbose_name='Цвет машины')),
                ('car_class', models.CharField(choices=[('Эконом (класс B)', 'Эконом (класс B)'), ('Средний (класс C)', 'Средний (класс C)'), ('Бизнес (класс Е)', 'Бизнес (класс Е)'), ('Кроссовер (класс J)', 'Кроссовер (класс J)')], max_length=255, verbose_name='Класс машины')),
                ('year', models.CharField(max_length=255, verbose_name='Год выпуска')),
                ('engine_cap', models.CharField(max_length=255, verbose_name='Объем двигателя')),
                ('engine_pow', models.CharField(max_length=255, verbose_name='Мощность двигателя')),
                ('gear_box', models.CharField(choices=[('Автомат', 'Автомат'), ('Механика', 'Механика'), ('Вариатор', 'Вариатор')], max_length=255, verbose_name='Коробка передач')),
                ('fuel_type', models.CharField(choices=[('АИ-95', 'АИ-95'), ('АИ-92', 'АИ-92'), ('АИ-93', 'АИ-93'), ('АИ-80', 'АИ-80'), ('Дизель', 'Дизель'), ('Электро', 'Электро')], max_length=255, verbose_name='Тип топлива')),
                ('fuel_tank', models.CharField(max_length=255, verbose_name='Объекм бака')),
                ('car_body', models.CharField(choices=[('Хэтчбек', 'Хэтчбек'), ('Кроссовер', 'Кроссовер'), ('Седан', 'Седан')], max_length=255, verbose_name='Кузов машины')),
                ('wd', models.CharField(choices=[('Полный', 'Полный'), ('Передний', 'Передний'), ('Задний', 'Задний')], max_length=255, verbose_name='Привод машины')),
                ('mileage', models.CharField(max_length=255, verbose_name='Потребление топлива')),
                ('vin', models.CharField(max_length=255, verbose_name='Идентификационный номер (VIN)')),
                ('registration', models.CharField(max_length=255, verbose_name='Свидетельство о регистрации ТС')),
                ('price_1_2', models.IntegerField(verbose_name='Цена от 1-2 дня')),
                ('price_3_7', models.IntegerField(verbose_name='Цена от 3-7 дней')),
                ('price_8_20', models.IntegerField(verbose_name='Цена от 8-20 дней')),
                ('price_20', models.IntegerField(verbose_name='Цена от 20 дней')),
                ('image1', models.ImageField(default='default.png', upload_to='cars/', verbose_name='Картинка 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Картинка 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Картинка 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Картинка 4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Картинка 5')),
                ('function_car', models.ManyToManyField(to='cars.FunctionCar', verbose_name='Функции машины')),
            ],
        ),
    ]
