# Generated by Django 4.1.6 on 2023-02-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_body',
            field=models.CharField(choices=[('Хэтчбек', 'Хэтчбек'), ('Кроссовер', 'Кроссовер'), ('Седан', 'Седан'), ('Лифтбек', 'Лифтбек'), ('Внедорожник', 'Внедорожник'), ('Стретч', 'Стретч'), ('Купе', 'Купе'), ('Родстер', 'Родстер'), ('Кабриолет', 'Кабриолет'), ('Фургон', 'Фургон'), ('Минивэн', 'Минивэн'), ('Пикап', 'Пикап'), ('Тарга', 'Тарга'), ('Универсал', 'Универсал')], max_length=255, verbose_name='Кузов машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(verbose_name='Описание машины'),
        ),
    ]
